-- Phase 1 production target schema (Supabase/Postgres). Local vertical slice uses data/store.json.
create extension if not exists pgcrypto;
create type signal_state as enum ('CANON','LIVE','SIMULATION','RAW','PROPOSED');
create type participant_type as enum ('resident','human','external_agent','system');
create table resident_agents(id text primary key,name text not null,philosophy text not null,config jsonb not null default '{}');
create table external_agents(id text primary key,name text not null,verified boolean not null default false,agent_card jsonb,first_seen timestamptz not null default now(),last_seen timestamptz not null default now());
create table debate_rooms(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,topic text not null,state signal_state not null,active boolean not null default true,created_at timestamptz not null default now());
create table provenance_records(id uuid primary key default gen_random_uuid(),origin_type text not null,origin_id text not null,verified_identity boolean not null default false,source_model text,transformations jsonb not null default '[]',canon_mutable boolean not null default false,created_at timestamptz not null default now());
create table messages(id uuid primary key default gen_random_uuid(),room_id uuid references debate_rooms(id),participant_id text not null,participant_name text not null,participant_type participant_type not null,content text not null,citations jsonb not null default '[]',interpretation boolean not null default true,provenance_id uuid not null references provenance_records(id),created_at timestamptz not null default now());
create table canon_entries(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,summary text not null,source_ref text not null,immutable boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table contributions(id uuid primary key default gen_random_uuid(),title text not null,body text not null,state signal_state not null check(state in ('PROPOSED','RAW')),origin_type text not null,origin_id text not null,provenance_id uuid not null references provenance_records(id),created_at timestamptz not null default now());
create table live_events(id uuid primary key default gen_random_uuid(),title text not null,summary text not null,verification_state text not null,confidence numeric,publication_time timestamptz,retrieved_at timestamptz not null default now(),metadata jsonb not null default '{}');
create table signal_sources(id uuid primary key default gen_random_uuid(),live_event_id uuid references live_events(id),url text not null,source_type text,claims jsonb not null default '[]',retrieved_at timestamptz not null default now());
create table audit_events(id bigserial primary key,actor_type text not null,actor_id text,action text not null,target_type text,target_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table cost_events(id bigserial primary key,provider text not null,model text,operation text not null,cost_usd numeric not null default 0,tokens_in bigint,tokens_out bigint,created_at timestamptz not null default now());
-- Canon cannot be directly written by untrusted runtime roles; enforce with RLS/service roles in deployment.
